1. Create a class Employee and then do the following:

* Create a data member to count the number of Employees
* Create a constructor to initialize name, family, salary, department
* Create a function to average salary
* Create a Fulltime Employee class and it should inherit the properties of Employee class
* Create the instances of Fulltime Employee class and Employee class and call their member functions.


In [5]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sowmya", "Vemula", 120000, "Development")
employee2 = Employee("Sahithi", "Vemula", 80000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Suresh", "Kumar", 40000, "Security")
fulltime_employee2 = FulltimeEmployee("Sudha", "Vani", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 50000.0
Average Salary for Fulltime Employees: 25000.0


Using NumPy:

* create random vector of size 20 having only float in the range 1-20.
* Then reshape the array to 4 by 5
* Then replace the max in each row by 0 (axis=1)

Note: (you can NOT implement it via for loop)

In [6]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [14.96223913 19.78363875 16.16059158  1.19534749  9.57627263  4.60751503
 15.8248341  15.20785251 13.17458167 13.39997966 17.08968673 13.03298829
 17.94194731  1.62820864 12.11857698 16.01850359 15.85006242 15.08553191
 18.19973292  8.86359358]


In [7]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[14.96223913 19.78363875 16.16059158  1.19534749  9.57627263]
 [ 4.60751503 15.8248341  15.20785251 13.17458167 13.39997966]
 [17.08968673 13.03298829 17.94194731  1.62820864 12.11857698]
 [16.01850359 15.85006242 15.08553191 18.19973292  8.86359358]]


In [8]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[14.96223913  0.         16.16059158  1.19534749  9.57627263]
 [ 4.60751503  0.         15.20785251 13.17458167 13.39997966]
 [17.08968673 13.03298829  0.          1.62820864 12.11857698]
 [16.01850359 15.85006242 15.08553191  0.          8.86359358]]
