1. Create a class Employee and then do the following:

* Create a data member to count the number of Employees
* Create a constructor to initialize name, family, salary, department
* Create a function to average salary
* Create a Fulltime Employee class and it should inherit the properties of Employee class
* Create the instances of Fulltime Employee class and Employee class and call their member functions.


In [1]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Nava Sai", "Gangireddy", 100000, "HR")
employee2 = Employee("Reddy", "Gangireddy", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Kumar Reddy", "Gangireddy", 80000, "Finance")
fulltime_employee2 = FulltimeEmployee("Nava", "Gangireddy", 70000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)


Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 37500.0


Using NumPy:

* create random vector of size 20 having only float in the range 1-20.
* Then reshape the array to 4 by 5
* Then replace the max in each row by 0 (axis=1)

Note: (you can NOT implement it via for loop)

In [2]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [15.50277551 18.50023186  3.954421   17.46235376 17.76126445 19.84431091
  6.4421753  13.3600551  18.56509297  4.88975197 19.00226087 16.17633014
  1.35350271 13.89463872  1.41986935 10.25100543 17.47375942  2.04498582
  2.58309421  4.03564164]


In [3]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[15.50277551 18.50023186  3.954421   17.46235376 17.76126445]
 [19.84431091  6.4421753  13.3600551  18.56509297  4.88975197]
 [19.00226087 16.17633014  1.35350271 13.89463872  1.41986935]
 [10.25100543 17.47375942  2.04498582  2.58309421  4.03564164]]


In [4]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[15.50277551  0.          3.954421   17.46235376 17.76126445]
 [ 0.          6.4421753  13.3600551  18.56509297  4.88975197]
 [ 0.         16.17633014  1.35350271 13.89463872  1.41986935]
 [10.25100543  0.          2.04498582  2.58309421  4.03564164]]
